---
- name: Loops Playbook
  hosts: slave
  become: yes

  tasks:
    - name: Say Hello to ALL
      debug: msg="Hello {{ item }}"
      loop: 
        - "Vlad"
        - "Alex"
        - "Oleg"

    - name: Loop Until example
      shell: echo -n Z >> myfile.txt && cat myfile.txt
      register: output #переменная
      delay: 2 #задeржка
      retries: 10 #Количество шагов
      until: output.stdout.find ("ZZZZ") == false #условие проверяте переменную output пока на экране не появиться ZZZZZ 

    - name: Print Final Output
      debug:
        var: output.stdout 
    
    - name: Install many packeges
      apt: name={{ item }} state=latest
      loop:
        - mc
        - tree
        - lm-sensors